spring.config.import=optional:configserver:http://localhost:8888
spring.application.name=auth-service

spring.cloud.config.profile=dev

server.port=${auth-service.port}


eureka.client.service-url.defaultZone=${auth-service.urlregistry}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

# JWT
jwt.secret=${smartmobility-secret-key-very-long-and-secure-2024-senegal}
jwt.expiration=${auth-service.expiration}

# Envoyer 100% des traces (1.0 = 100%, 0.1 = 10%)
management.tracing.sampling.probability=1.0

# URL du serveur Zipkin
management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans

spring.cloud.config.retry.max-attempts=3
spring.cloud.config.retry.initial-interval=1000



