spring.config.import=optional:configserver:http://localhost:8888
spring.application.name=notification-service

spring.cloud.config.profile=dev

server.port=${notification-service.port}

spring.datasource.url=${notification-service.mysql.url}
spring.datasource.username=${notification-service.mysql.username}
spring.datasource.password=${notification-service.mysql.password}
spring.datasource.driver-class-name=${notification-service.mysql.driver-class-name}

spring.jpa.hibernate.ddl-auto=${notification-service.jpa.hibernate.ddl-auto}
spring.jpa.show-sql=${notification-service.jpa.show-sql}
spring.jpa.properties.hibernate.dialect=${notification-service.jpa.properties.hibernate.dialect}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

eureka.client.service-url.defaultZone=${eureka.client.service-url.defaultZone}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}
