# Config Server Connection
spring.config.import=optional:configserver:http://localhost:8888

# Service Identity
spring.application.name=pricing-discount-service
spring.profiles.active=dev

# Port
server.port=${pricing-discount-service.port}

# Eureka Client
eureka.client.service-url.defaultZone=${pricing-discount-service.urlregistry}
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logging
logging.level.com.smartmobility.pricing=INFO