spring.config.import=optional:configserver:http://localhost:8888
spring.application.name=billing-service

spring.cloud.config.profile=dev

server.port=${billing-service.port}

spring.datasource.url=${billing-service.mysql.url}
spring.datasource.username=${billing-service.mysql.username}
spring.datasource.password=${billing-service.mysql.password}
spring.datasource.driver-class-name=${billing-service.mysql.driver-class-name}

spring.jpa.hibernate.ddl-auto=${billing-service.jpa.hibernate.ddl-auto}
spring.jpa.show-sql=${billing-service.jpa.show-sql}
spring.jpa.properties.hibernate.dialect=${billing-service.jpa.properties.hibernate.dialect}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

eureka.client.service-url.defaultZone=${eureka.client.service-url.defaultZone}