api-gateway.uriport=8765
api-gateway.discovery.locator=true
api-gateway.discovery.locator.lower-case-service-id=true

api-gateway.urlregistry=http://localhost:8761/eureka

api-gateway.secret=smartmobility-secret-key-very-long-and-secure-2024-senegal
api-gateway.expiration=86400000