# Ajouts de Aziz — Configuration centralisée dev pour eureka-server — 2026-02-21
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false
management.endpoints.web.exposure.include=health,info,metrics
