user-mobility-pass-service.type=unique-default
user-mobility-pass-service.name=SRV-DEV-EUREKA-REGISTRY-SERVER-UNKO01

pricing-discount-service.type=unique-default
pricing-discount-service.namee=SRV-DEV-EUREKA-REGISTRY-SERVER-UNKO01

billing-service.type=unique-default
billing-service.namee=SRV-DEV-EUREKA-REGISTRY-SERVER-UNKO01

notification-service.type=unique-default
notification-service.namee=SRV-DEV-EUREKA-REGISTRY-SERVER-UNKO01


eureka-server.fetchregistry=true
eureka-server.uriport=8761