# Service Configuration
pricing-discount-service.type=unique-default
pricing-discount-service.name=Pricing-discount-Service
pricing-discount-service.profile=dev
pricing-discount-service.port=8084

pricing-discount-service.urlregistry=http://localhost:8761/eureka