# Service Configuration
trip-management-service.type=unique-default
trip-management-service.name=Trip-Management-Service
trip-management-service.profile=dev
trip-management-service.port=8083

# MySQL Database Configuration
trip-management-service.mysql.url=jdbc:mysql://localhost:3306/smart_mobility_trip_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
trip-management-service.mysql.username=root
trip-management-service.mysql.password=root
#trip-management-service.mysql.password=
trip-management-service.mysql.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
trip-management-service.jpa.hibernate.ddl-auto=update
trip-management-service.jpa.show-sql=true
trip-management-service.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

trip-management-service.RABBITMQ_HOST=localhost
trip-management-service.RABBITMQ_PORT=5672
trip-management-service.RABBITMQ_USER=guest
trip-management-service.RABBITMQ_PASS=guest