spring.application.name=pricing-discount-service
spring.config.import=optional:configserver:http://localhost:8888
server.port=${pricing-discount-service.port}
eureka.client.service-url.defaultZone=${pricing-discount-service.urlregistry}

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always