spring.application.name=api-gateway
spring.config.import=optional:configserver:http://localhost:8888

server.port=${api-gateway.uriport}

eureka.client.service-url.defaultZone=${api-gateway.urlregistry}

#spring.cloud.gateway.server.webflux.discovery.locator.enabled=${api-gateway.discovery.locator}

spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=${api-gateway.discovery.locator.lower-case-service-id}