spring.application.name=api-gateway
spring.config.import=optional:configserver:http://localhost:8888

server.port=${api-gateway.uriport}

eureka.client.service-url.defaultZone=${api-gateway.urlregistry}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${api-gateway.uriport}

#spring.cloud.gateway.server.webflux.discovery.locator.enabled=${api-gateway.discovery.locator}

spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=${api-gateway.discovery.locator.lower-case-service-id}

# Envoyer 100% des traces (1.0 = 100%, 0.1 = 10%)
management.tracing.sampling.probability=1.0

# URL du serveur Zipkin
management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans