spring.config.import=optional:configserver:http://localhost:8888
spring.application.name=trip-management-service

spring.cloud.config.profile=dev

server.port=${trip-management-service.port}

spring.datasource.url=${trip-management-service.mysql.url}
spring.datasource.username=${trip-management-service.mysql.username}
spring.datasource.password=${trip-management-service.mysql.password}
spring.datasource.driver-class-name=${trip-management-service.mysql.driver-class-name}

spring.jpa.hibernate.ddl-auto=${trip-management-service.jpa.hibernate.ddl-auto}
spring.jpa.show-sql=${trip-management-service.jpa.show-sql}
spring.jpa.properties.hibernate.dialect=${trip-management-service.jpa.properties.hibernate.dialect}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

eureka.client.service-url.defaultZone=${eureka.client.service-url.defaultZone}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

spring.rabbitmq.host=${trip-management-service.RABBITMQ_HOST}
spring.rabbitmq.port=${trip-management-service.RABBITMQ_PORT}
spring.rabbitmq.username=${trip-management-service.RABBITMQ_USER}
spring.rabbitmq.password=${trip-management-service.RABBITMQ_PASS}

