spring.application.name=eureka-server
spring.config.import=optional:configserver:http://localhost:8888
server.port=${eureka-server.uriport}

spring.cloud.config.profile=dev
eureka.client.fetch-registry=${eureka-server.fetchregistry}