spring.application.name=config-server
server.port=8888

# 1. On force Spring Cloud Config à utiliser les fichiers locaux (désactive Git et le SSH)
spring.profiles.active=native

# 2. On indique le chemin exact du dossier contenant les fichiers .properties (équivalent de uri + search-paths)
#spring.cloud.config.server.native.search-locations=file:///C:/IntegrationDeService/Smart-mobility-pass/config
spring.cloud.config.server.native.search-locations=file:/Users/macbook/Downloads/Smart-mobility-pass/config